# Generated by Django 2.2.3 on 2019-07-11 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0002_auto_20190710_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokeballs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, unique=True)),
                ('catchRate', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, unique=True)),
                ('catchChance', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('spawnChance', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, unique=True)),
                ('token', models.CharField(blank=True, max_length=248, unique=True)),
                ('items', models.CharField(blank=True, max_length=64)),
                ('area_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='areas',
            name='adjacents',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='areas',
            name='description',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='areas',
            name='pokeballs',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='areas',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='areas',
            name='pokemon',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
