# Generated by Django 2.2.3 on 2019-07-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0003_auto_20190710_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeballs',
            name='catchRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='catchChance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='spawnChance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
