# Generated by Django 2.2.3 on 2019-07-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0004_auto_20190710_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeballs',
            name='catchRate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4),
        ),
    ]
