# Generated by Django 2.2.3 on 2019-07-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0008_auto_20190711_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areas',
            old_name='adjacents',
            new_name='exits',
        ),
        migrations.AddField(
            model_name='areas',
            name='coords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
