# Generated by Django 2.2.3 on 2019-07-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0010_auto_20190715_2039'),
        ('mud', '0009_auto_20190715_2056'),
    ]

    operations = [
    ]
