# Generated by Django 2.2.3 on 2019-07-16 03:02

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0011_merge_20190715_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='pokeballs',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
    ]
