# Generated by Django 2.2.3 on 2019-07-16 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0012_auto_20190715_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areas',
            old_name='exits',
            new_name='adjacents',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='coords',
        ),
        migrations.AlterField(
            model_name='areas',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokeballs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
