# Generated by Django 2.2.3 on 2019-07-16 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0015_auto_20190715_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areas',
            old_name='id',
            new_name='areaId',
        ),
        migrations.RenameField(
            model_name='pokeballs',
            old_name='id',
            new_name='pokeballId',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='id',
            new_name='pokemonId',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='id',
            new_name='userId',
        ),
    ]
