# Generated by Django 2.2.3 on 2019-07-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0016_auto_20190715_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='token',
            new_name='password',
        ),
    ]
