# Generated by Django 2.2.3 on 2019-07-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0020_remove_users_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
    ]
