# Generated by Django 2.2.3 on 2019-07-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0021_auto_20190721_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pokemon',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
    ]
