# Generated by Django 2.2.3 on 2019-07-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0022_users_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pokeballs',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='pokeballs',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='pokemon',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
    ]
