# Generated by Django 2.2.3 on 2019-07-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0023_auto_20190722_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='items',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
    ]
